### ISSUE TITLE
transforms perform very slow

### ISSUE THREAD

**Issue by alexbodn** [jvail/spl.js#26]
one last bug for now,

i'm using spl.js on a phone.
now it's a faster one, but my first ever spatial query still needs some attention.

the following query runs 2.7s for the first time, and  0.5s the subsequent times.
on my older phone, 8s and 1.7s. technology progresses.

select 
st_transform(
st_transform(
MakePoint (-22562.401432422717, 6730934.887787993, 3857)
, 27700)
, 3857);

to counter this problem, i used proj4js, which is unexplicably faster, though i didn't specifically measure.

spatialite, on a computer does that in miliseconds.

please be so kind and look at this issue.

**Comment by jvail** [comment]
I suggest to add an `await` here https://github.com/alexbodn/sqlitexplorer/blob/82efe44d1500af0ba114b7f0befefa5fbc57029a/examples.html#L121

The first transform is so slow because it still needs to fetch the proj.db file. 0.5 s seems reasonable on a mobile. It takes ~250 ms on my desktop. I guess your timing includes the worker communication.

Here https://github.com/alexbodn/sqlitexplorer/blob/82efe44d1500af0ba114b7f0befefa5fbc57029a/examples.html#L128 `read` wont do anything until you await so there is nothing to catch.

**Comment by jvail** [comment]
I have seen some issues regarding performance in different versions of the proj library. Not sure what versions you were using for the comparison. spl.js is currently build with  9.3.1. I wonder if that might explain some differences.

**Comment by alexbodn** [comment]
your post more than explains my situation.
after installing the last spl.js, the projections ran acceptably fast, even with selecting all the geom features in london_boroughs.

and i wanted to see whether it's something else I missed, but in the meantime you posted and saved me some work.

**Comment by alexbodn** [comment]
Database manipulation involves heavy resources, as disk and network i/o and walking big data structures.

As all these activities are generally needed, the most a developer can do is reducing the loops that summon these heavy operations.
One example is the date('now') function, that is called once in a query run, see:

SELECT
(STRFTIME('%Y-%m-%d %H:%M:%f', 'NOW')) as now,
[geom]
from [london_boroughs]

By analogy, I'd also cache the projection definition upon the first record in a query where st_transform is run.

Sometimes, the user has the opportunity to design queries that may reduce the loops that execute st_transform.

for example, I'm creating a geometry aggregate, so
so that st_transform will run only once.

select
st_transform(
collect(
[geom]
)
, 4326)
 as feature
from [london_boroughs]

The proof that the efficiency of the function itself has been improved, is that there's no significant difference whether when st_transform is run  once on the collected aggregate, or once for every retrieved row.6

**Comment by jvail** [comment]
Thanks for the feedback. I made a little script to test the performance inside the worker:

```html
<pre id="time"></pre>
<script type="module">

    import SPL from '../dist/index.js';

    const extension = {
        extends: 'db',
        fns: {
            'transform': db => {
                const time = []
                for (let i = 0; i < 50; i++) {
                    const t = Date.now();
                    db.exec("select st_transform(st_transform(MakePoint (-22562.401432422717, 6730934.887787993, 3857), 27700), 3857)");
                    time.push(Date.now() - t);
                }
                return time;
            }
        }
    };

    const proj = await fetch('../dist/proj/proj.db').then(data => data.arrayBuffer())
    const spl = await SPL({}, [extension]);
    const db = await spl
                .mount('proj', [
                    { name: 'proj.db', data: proj }
                ])
                .db()
                    .read(`
                        select PROJ_SetDatabasePath('/proj/proj.db');
                        select initspatialmetadata(1);
                    `);

    const el = document.getElementById("time")
    el.innerHTML = await db.transform();

</script>
```
```
215,180,147,141,168,161,143,156,156,142,105,103,105,100,100,99,104,99,62,63,62,64,63,61,63,67,61,63,61,61,62,61,63,61,61,62,60,65,61,61,61,69,62,61,61,61,62,60,63,62
```

Interestingly the time decreases to ~60 ms

**Comment by jvail** [comment]
Guess this is "solved" ...

**Comment by alexbodn** [comment]
> Guess this is "solved" ...

sure, for real data conditions everything worked very fast.

**Comment by alexbodn** [comment]
215,180,147,141,168,161,143,156,156,142,105,103,105,100,100,99,104,99,62,63,62,64,63,61,63,67,61,63,61,61,62,61,63,61,61,62,60,65,61,61,61,69,62,61,61,61,62,60,63,62
> ```
> 
> Interestingly the time decreases to ~60 ms

well here're my measurements
  
//with previous spl.js   //1787,474,501,613,435,534,800,628,503,672,494,468,670,665,643,570,642,530,737,552,762,643,718,542,712,755,691,581,656,759,724,608,781,532,764,769,546,709,855,728,425,389,660,830,593,810,695,877,799,867
 
//with spl.js you provided.   //1871,397,405,500,474,631,779,564,445,401,634,446,682,973,636,630,745,507,569,583,677,673,709,657,645,598,673,809,903,949,847,959,586,777,874,700,609,784,907,598,758,699,790,636,610,678,1052,994,823,806

//no big difference, but for real life data, thw speed is acceptable.

**Comment by jvail** [comment]
@alexbodn Oh, that seems slow. Was it on your "old" or your "new" phone? The new release only fixed the issue with fetching the png blobs not the "slowness" of transforms.

**Comment by alexbodn** [comment]
> @alexbodn Oh, that seems slow. Was it on your "old" or your "new" phone? The new release only fixed the issue with fetching the png blobs not the "slowness" of transforms.

this is my newer phone.
i thought  your new version changed also proj, since i vaguely remembered some 9.2.2 proj_version().
now i see both have proj 9.3.1. my bad.

however, i'm projecting thousands of points in one direction, faster than that 1 point example.
