### ISSUE TITLE
  Electron - ReferenceError: Worker is not defined

### ISSUE THREAD

**Issue by ahrimov** [jvail/spl.js#27]
Have testing spl.js with electron and got this error "ReferenceError: Worker is not defined".
Here is my code (main.js - Node.js environment):

```
import { app, BrowserWindow } from 'electron';
import SPL from 'spl.js';

const createWindow = async () => {
    const spl =  await SPL(); // getting errorMessage on this line
    const db = await spl.db();
}

app.whenReady().then(() => {
    createWindow();
});
```

package.json:

```
{
  "name": "y",
  "version": "1.0.0",
  "description": "\"Desktop electron app\"",
  "main": "main.js",
  "type": "module",
  "scripts": {
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^29.1.4"
  },
  "dependencies": {
    "spl.js": "^0.1.1"
  }
}
```
What am I doing wrong? Please help me!

**Comment by jvail** [comment]
If you run spl in node you need to import the `mjs` which has a fully synchronous api: https://github.com/jvail/spl.js/blob/586266bc2e7317e30f70b8c8593278f9670eb908/test/node.js#L10

I guess if you use the `BrowserWindow` then you need to load it there. For example inside the index.html: `win.loadFile('index.html')`. I seems in your example it still runs in node - with no worker api available.
