### ISSUE TITLE
ST_Transform throwing error

### ISSUE THREAD

**Issue by abenrob** [jvail/spl.js#9]
Hello ! 
I'm trying to expand my proposed series on spl.js, and I came across an issue - 

When trying to use `ST_Transform()`, I get `Error: ST_Transform exception - PROJ reports "proj_create: no database context specified".`

The test SQL: `SELECT ST_Buffer(ST_Transform(MakePoint(5.7245, 45.1885,4326),3857), 200);`

Is this from the lib, or my src DB, or the sqlite version at Observable, or something else?

https://observablehq.com/d/b250322cbcc02b2f

**Comment by abenrob** [comment]
Thanks. Trying it out now. Are there resources for building this? If my examples only need 3857 & 4326, I wonder if I could compile a version only containing those...

**Comment by abenrob** [comment]
> Thanks. Trying it out now. Are there resources for building this? If my examples only need 3857 & 4326, I wonder if I could compile a version only containing those...

I'll keep the ticket closed, but any info on where `proj.db` comes from,and how to build it will be appreciated!

**Comment by abenrob** [comment]
> Nice notebook example! I'll add a link to the readme once it is done.

https://observablehq.com/@abenrob/sqlite-geospatial-buffers

**Comment by jvail** [comment]
Thanks fro the PR & very nice notebook! Just one thing I noticed (not important): mapbox seems to have an issue updating the canvas. When I move the slider some parts of the previous buffer are still visible.

**Comment by abenrob** [comment]
Hm - what browser/os ? I don't see that effect on mine, but I only test what I use habitually...

**Comment by jvail** [comment]
![Peek 2022-06-28 12-00](https://user-images.githubusercontent.com/6503378/176152106-c677534e-8795-409a-8943-1f7ba4be758a.gif)

I am using the latest FF.

**Comment by jvail** [comment]
Just tested in chrome and it is completely smooth - seems it is a FF thing.
